project_id = "oxwhqvsoelqqsblmqkxx"

[functions.ai-doubt-clear]
verify_jwt = true

[functions.ai-generate-mcqs]
verify_jwt = true

[functions.ai-tutor-chat]
verify_jwt = true

[functions.ai-rephrase]
verify_jwt = true

[functions.ai-generate-video]
verify_jwt = true

[functions.ai-generate-podcast]
verify_jwt = true

[functions.create-payment-order]
verify_jwt = false
